spring:
  datasource:
    url: jdbc:mysql://localhost:3306/framework?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9090